import { Objekt, Wohnung } from "./häuser";
import { v4 as uuidv4 } from 'uuid';
const UserId = uuidv4();
export const HauserNEU : Objekt[] = [
{
    id: uuidv4(),
	Erstelltam: new Date(),
	Firma:'Nix',
	Bezeichnung: 'Test',
	Adresse: 'DeineMutter',
    Preis: 1234,
	Nebenkosten: 123456,
	Typ: 'Teest',
	PLZ: 123456789,
	Stadt: 'Nixhausen',
	Wohnfläche: 45,
	Etagen: 2,
	Baujahr: 1952,
	Energieklasse: 'AA',
	Heizung: 'Gas',
    Beschreibung: "Schönes Haus, in einer Wohlfühlarea, welche Sie noch nie gesehen haben",
	Bezugsfrei: new Date(),
    Garagenstellplatz: true,
},
{
	id: uuidv4(),
	Erstelltam: new Date(),
	Firma:'Nix',
	Bezeichnung: 'Test',
	Adresse: 'DeineMutter',
    Preis: 1234,
	Nebenkosten: 123456,
	Typ: 'Teest',
	PLZ: 123456789,
	Stadt: 'Nixhausen',
	Wohnfläche: 45,
	Etagen: 2,
	Baujahr: 1952,
	Energieklasse: 'AA',
	Heizung: 'Gas',
    Beschreibung: "Schönes Haus, in einer Wohlfühlarea, welche Sie noch nie gesehen haben",
	Bezugsfrei: new Date(),
    Garagenstellplatz: true,
}

];

export const WohnungenNEU : Objekt[] = [
    {
		id: uuidv4(),
		Erstelltam: new Date(),
		Firma:'Nix',
		Bezeichnung: 'Test',
		Adresse: 'DeineMutter',
		Preis: 1234,
		Nebenkosten: 123456,
		Typ: 'Teest',
		PLZ: 123456789,
		Stadt: 'Nixhausen',
		Wohnfläche: 45,
		Etagen: 2,
		Baujahr: 1952,
		Energieklasse: 'AA',
		Heizung: 'Gas',
		Beschreibung: "Schönes Haus, in einer Wohlfühlarea, welche Sie noch nie gesehen haben",
		Bezugsfrei: new Date(),
		Garagenstellplatz: true,
    },
    {
		id: uuidv4(),
		Erstelltam: new Date(),
		Firma:'Nix',
		Bezeichnung: 'Test',
		Adresse: 'DeineMutter',
		Preis: 1234,
		Nebenkosten: 123456,
		Typ: 'Teest',
		PLZ: 123456789,
		Stadt: 'Nixhausen',
		Wohnfläche: 45,
		Etagen: 2,
		Baujahr: 1952,
		Energieklasse: 'AA',
		Heizung: 'Gas',
		Beschreibung: "Schönes Haus, in einer Wohlfühlarea, welche Sie noch nie gesehen haben",
		Bezugsfrei: new Date(),
		Garagenstellplatz: true,
    },
    {
		id: uuidv4(),
		Erstelltam: new Date(),
		Firma:'Nix',
		Bezeichnung: 'Test',
		Adresse: 'DeineMutter',
		Preis: 1234,
		Nebenkosten: 123456,
		Typ: 'Teest',
		PLZ: 123456789,
		Stadt: 'Nixhausen',
		Wohnfläche: 45,
		Etagen: 2,
		Baujahr: 1952,
		Energieklasse: 'AA',
		Heizung: 'Gas',
		Beschreibung: "Schönes Haus, in einer Wohlfühlarea, welche Sie noch nie gesehen haben",
		Bezugsfrei: new Date(),
		Garagenstellplatz: true,
    },
]